server:
  port: ${SERVER_PORT:9000}
  error:
    include-message: always

spring:
  application:
    name: file-api

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:file}
  username: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:postgres123}
  connectionPool:
    maxSize: ${MAX_POOL_SIZE:10}
    initialSize: ${INITIAL_POOL_SIZE:5}
    maxIdleTime: ${MAX_IDLE_TIME:PT30M}
    maxCreateConnectionTime: ${MAX_CREATE_CONNECTION_TIME:PT5S}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

file:
  upload: ./files
