server:
  port: ${SERVER_PORT:9000}
  error:
    include-message: always

spring:
  application:
    name: file-api

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:file}
  username: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:postgres123}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

file:
  upload: ./files
